### PR TITLE
Replace wget with curl

### PR DESCRIPTION
**Pull request by hishamhm**
I've had problems with the latest version of wget downloading from some IPv6 servers. Looking around, it seems I wasn't the only one to have some problems with wget, so I decided to give curl a shot.

### CODE REVIEW

**Comment by lucasvr** [comment]
I've noticed an error when typing Compile to build a new version of the PostGIS recipe, whose most recent version in the recipe store is 2.3.1. When I type `Compile PostGIS 2.4.3`, a new recipe is generated and soon afterwards the process crashes:

```
Compile: Checking dependencies...
/usr/bin/Compile: line 478: HTTP/1.1 200 OK
Date: Wed, 28 Feb 2018 20:54:02 GMT
Server: Apache/2.2.22
Strict-Transport-Security: max-age=15768000
Last-Modified: Tue, 16 Jan 2018 07:33:48 GMT
ETag: "1d8127-c046df-562dfc05b6f00"
Accept-Ranges: bytes
Content-Length: 12601055
Content-Type: application/x-gzip

/Data/Compile/LocalRecipes/PostGIS/2.4.3/Recipe: No such file or directory
Compile: Compiling PostGIS version 2.4.3.
/usr/bin/Compile: line 478: HTTP/1.1 200 OK
Date: Wed, 28 Feb 2018 20:54:02 GMT
Server: Apache/2.2.22
Strict-Transport-Security: max-age=15768000
Last-Modified: Tue, 16 Jan 2018 07:33:48 GMT
ETag: "1d8127-c046df-562dfc05b6f00"
Accept-Ranges: bytes
Content-Length: 12601055
Content-Type: application/x-gzip

/Data/Compile/LocalRecipes/PostGIS/2.4.3/Recipe: No such file or directory
Compile: Missing URL or repository information in recipe 'HTTP/1.1 200 OK
Date: Wed, 28 Feb 2018 20:54:02 GMT
Server: Apache/2.2.22
Strict-Transport-Security: max-age=15768000
Last-Modified: Tue, 16 Jan 2018 07:33:48 GMT
ETag: "1d8127-c046df-562dfc05b6f00"
Accept-Ranges: bytes
Content-Length: 12601055
Content-Type: application/x-gzip

/Data/Compile/LocalRecipes/PostGIS/2.4.3/Recipe'.
```

**Comment by lucasvr** [comment]
I have also noticed that MakeRecipe is not honoring --no-check-certificate. For some strange reason the Boolean test is not catching it. Would you mind to double check that?

**Comment by hishamhm** [comment]
@lucasvr I also realized that curl doesn't do redirects by default, I needed to add `-L` to every invocation. I'll push that fix to this PR and also check the issues you wrote about, thank you for trying it out!

**Comment by hishamhm** [comment]
As an update, I've been using this — it mostly works but it still has some rough edges. Not ready for merging yet.

**Pull request closed without merging**
