### PR TITLE
Use new Runner flags in Compile

### PR DESCRIPTION
**Pull request by AitorATuin**
Let Runner use the new flags and show some messages about what's going on.

See this: https://github.com/gobolinux/Scripts/pull/5

### CODE REVIEW

**Comment by lucasvr** [comment]
Aitor, I wonder what's the benefit of re-spawning with Runner if we know that the sandbox cannot be created?

**Comment by AitorATuin** [comment]
None, but it how it was working before (https://github.com/gobolinux/Compile/blob/master/bin/Compile#L298) :)
 I agree that it's a non-sense so I will remove it (I really wanted to do it from the beginning)

**Comment by hishamhm** [comment]
I do prefer the fallback behavior in `Runner`, so that `Runner foo` always runs (with or without the overlay). It does print a warning anyway, so I think it will produce less friction when using Runner from the command line. Keeping it as it was produces the same end result (a warning message and the program running without the overlay), only with less code and forks.

**Comment by AitorATuin** [comment]
I don't see the point. I agree that enabling a default fallback has less friction for the user but i feel it very counterintuitive. The main purpose of Runner is run a program inside a sandbox so me (as unix user) I'm expecting it to do nothing if the sandbox is not available and to give it a flag if I want to force the execution of the program.
This also has the benefit of a better interface to script against it, more control on how the program is working.
@lucasvr what do you think?

**Comment by hishamhm** [comment]
@AitorATuin Fair points, I'm convinced. The behavior of Compile, which is the higher-level interface, will be frictionless (for both main scenarios: on 016 systems people will have 4.0+ anyway, and in Rootless they won't have suid Runner). When using Runner directly, people will want more control.

**Comment by hishamhm** [comment]
(I'll just lower the log level of the messages a bit)

**Pull request merged**
